export const ALL_PRODUCTS = "/products"
export const ALL_CATEGORIES = "/products/categories/"
export const PRODUCTS_BY_CATEGORY = "/products/category/"
export const CART = "/carts"
export const USER = "/users"