export const ALL_PRODUCTS = "/products"
export const ALL_CATEGORIES = "/products/categories/"
export const PRODUCTS_BY_CATEGORY = "/products/category/"
export const ADDTOCART = "/carts/add"
export const VIEWCART = "/carts/user/5"
export const USER = "/users"